### ISSUE TITLE
Dumps error output into document

### ISSUE THREAD

**Issue by garrettw** [wongjn/vscode-php-sniffer#10]
**Describe the bug**
Just now, when copying and pasting the word `false`, upon pasting I got these two notices dumped into my document at the paste point, following by what I was trying to paste:
```
Notice: Undefined offset: 2 in /Users/username/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Tokenizers/PHP.php on line 1369

Notice: Undefined offset: 2 in /Users/username/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Tokenizers/PHP.php on line 1380
false
```

**To Reproduce**
1. Copy the word `false` in a document
2. Highlight the word `true` in the same document
3. Cmd+V to paste over it
4. Get above output

**Expected behavior**
The word should have just been replaced with no notices being dumped -- or, if there were any notices, they should have been sent to the appropriate Output panel.

**Environment**
 - OS: macOS 10.14.3
 - VSCode version: 1.31.1
 - PHP CLI version: 7.1.23
-  squizlabs/PHP_CodeSniffer version: 2.9.1

**Extension settings**
none

**Comment by wongjn** [comment]
The extension in its current state does not necessarily support squizlabs/PHP_CodeSniffer version  `<3.0.0`. I would suggested updating to v3 if your tooling/workflow allows it. Sorry for the inconvenience this has caused you.

**Comment by garrettw** [comment]
Drupal's CS for PHPCS required <3.0.0 up until version 8.3.0 of the CS, which was released in Q3 of last year -- didn't realize that! I should be able to upgrade then. Thanks anyway.
