### ISSUE TITLE
Running with PHP inside docker

### ISSUE THREAD

**Issue by wongjn** [wongjn/vscode-php-sniffer#2]
I'm having the same problem, but my php is running inside a docker container, I have a ```/usr/bin/php``` that looks like this:
```shell
#!/bin/bash

docker exec \
    -it \
    -u $(id -u) \
    -w "$PWD" \
    php7 \
    php "$@"
```

_Originally posted by @elvishp2006 in https://github.com/wongjn/vscode-php-sniffer/issues/1#issuecomment-453065457_

> Are you running the latest version of the extension?
> What is the command to run `phpcs` with PHP in docker?
> Could you provide the settings you are using?

_@wongjn https://github.com/wongjn/vscode-php-sniffer/issues/1#issuecomment-453086504_

> Yes, I'm using the latest version of the extension.
> I got a script on my composer.json:
> 
> ```json
>   "scripts": {
>     "lint": "phpcs",
>     "lint:fix": "phpcbf"
>   }
> ```
> 
> I just need to run `composer lint` to run my phpcs.

_@elvishp2006 https://github.com/wongjn/vscode-php-sniffer/issues/1#issuecomment-453146180_

**Comment by wongjn** [comment]
So you cannot run `phpcs` command directly @elvishp2006?

**Comment by elvishp2006** [comment]
If I run the command `./vendor/bin/phpcs` it's still work fine, but the extension don't recognize that I have it installed, and I already changed the config to:
```json
"phpSniffer.executablesFolder": "./vendor/bin/phpcs"
```

**Comment by wongjn** [comment]
Try `./vendor/bin/` exactly instead; the setting is for the __folder__ that both `phpcs` and `phpcbf` are both in.

**Comment by elvishp2006** [comment]
I tried it now, not worked yet, the extension output a log somewhere?

**Comment by wongjn** [comment]
Yes, open devtools: Help > Toggle Developer Tools

**Comment by elvishp2006** [comment]
I'm getting some errors when I save my code: 
```
[Extension Host] the input device is not a TTY
```
```
[Extension Host] SyntaxError: Unexpected end of JSON input
```

**Comment by wongjn** [comment]
I've already solved `[Extension Host] SyntaxError: Unexpected end of JSON input` in dev but it also means that `phpcs` command has executed.

Not sure what `[Extension Host] the input device is not a TTY` is referring to. The extension creates a process and [feeds in the file content as `stdin`](https://github.com/wongjn/vscode-php-sniffer/blob/090ae4e388062cc664f8b06a111da106a82d421e/src/validator.ts#L177) - could this be incompatible with Docker?
The error about TTY may also to do with Docker CLI interactions [here](https://stackoverflow.com/questions/43099116/error-the-input-device-is-not-a-tty) and [here](https://serverfault.com/questions/897847/what-does-the-input-device-is-not-a-tty-exactly-mean-in-docker-run-output), etc?

**Comment by elvishp2006** [comment]
I got my phpcs working with the following:
* Replaced the `-it` arg for `-i` arg
**/usr/bin/php**
```shell
#!/bin/bash

docker exec \
    -i \
    -u $(id -u) \
    -w "$PWD" \
    php7 \
    php "$@"
```

But it yet wont work with a custom `"phpSniffer.standard": "./phpcs.xml"` configuration.
I'm getting the following output on console:
```
[Extension Host] [32mE[0m 1 / 1 (100%)


{"totals":{"errors":1,"warnings":0,"fixable":1},"files":{"STDIN":{"errors":1,"warnings":0,"messages":[{"message":"Expected 1 spaces after opening bracket; 0 found","source":"PEAR.Functions.FunctionCallSignature.SpaceAfterOpenBracket","severity":5,"fixable":true,"type":"ERROR","line":27,"column":16}]}}}
```

**Comment by elvishp2006** [comment]
I discovered what was causing it, was the following lines at my `phpcs.xml`:
```xml
	<arg value="sp"/> <!-- Show sniff and progress -->
	<arg name="colors"/> <!-- Show results with colors -->
```

There is a way to contorn it with these options?

**Comment by elvishp2006** [comment]
The extension is not following these configs:
```xml
	<!-- What to scan -->
	<file>.</file>
	<!-- Ignoring Files and Folders:
		https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-files-and-folders -->
	<exclude-pattern>api-reference/</exclude-pattern>
	<exclude-pattern>dist/</exclude-pattern>
	<exclude-pattern>node_modules/</exclude-pattern>
	<exclude-pattern>resources/</exclude-pattern>
	<exclude-pattern>vendor/</exclude-pattern>
	<!-- Scrutinizer dependency -->
	<exclude-pattern>wordpress/</exclude-pattern>
```
It's pointing errors at files inside vendor folder, but it's on exclude-pattern tag.

**Comment by wongjn** [comment]
Thank you. I'm glad we could get to the cause of your issues with this extension. These two points have been moved to separate issues.
