### ISSUE TITLE
Relative path to standard from ${workspaceFolder}\project-folder\.vscode\settings.json

### ISSUE THREAD

**Issue by dimaeromin97** [wongjn/vscode-php-sniffer#23]
**Describe the bug**
thanks for the great extension, perhaps the best phpcs for vscode, but I have

**To Reproduce**
If the folder is not the first in the workspace then nothing works even if I set the path to the settings for this folder: [screenshot](https://i.imgur.com/jFMdB5m.png)

**Environment**
 - OS: [e.g. Windows 10]
 - VSCode version: [e.g. 1.41.1]
 - PHP CLI version: [e.g. 7.2.0]
-  squizlabs/PHP_CodeSniffer version: [e.g. 3.4.0]

**Comment by wongjn** [comment]
Have you tried `".phpcs.xml"` or maybe `".\\.phpcs.xml"` (unsure on Windows path notation)?
Do other folder-scoped settings work?

**Comment by wongjn** [comment]
Resolved by commit 6e9a139.
