### ISSUE TITLE
Exclude folder options.

### ISSUE THREAD

**Issue by dimative** [wongjn/vscode-php-sniffer#24]
**Is your feature request related to a problem? Please describe.**
Hello. 
First thanks for the making this extension for developers. This extension saves many days of mine. I have some problem. I am a WordPress Developer. Yesterday i have little problem. I need to use external PHP library for my project. This library is huge, includes many many files. After added this library to my project phpcs linting was very slow. Sometimes fixer does not work. CPU loading is increased.

**Describe the solution you'd like**
I have an idea for this issue. I want to exclude huge library folder. Just want to sniff my project code. I tried to exclude folder from phpcs.xml.dist file. But can't get success. 

**Additional context**
Do you have any solution way like this problem? If you have it, please recommend me.

Thanks.

**Comment by wongjn** [comment]
Having many files in VSCode project does not proportionally increase resource usage of this extension. The extension only operates on currently open files in the editor window.

[Please see this comment](https://github.com/wongjn/vscode-php-sniffer/issues/19#issuecomment-503526502) to implement folder exclusion.
