### ISSUE TITLE
Passing VSCode's tab spacing option is unexpected

### ISSUE THREAD

**Issue by nuvoPoint** [wongjn/vscode-php-sniffer#26]
After upgrading to version 1.2.1 I get this error:
`Illegal argument: character must be non-negative`

After upgrading to version 1.2.2 the coding standards are not getting picked up correctly.
Running phpcs -i correctly shows my installed coding standards but VS Code shows errors all over the code. Downgrading to version 1.2.0 seems to work.

Any suggestions?

**Comment by wongjn** [comment]
The extension now passes the configured tab size from VSCode into the `phpcs` command as `--tab-width` argument so it can position diagnostics correctly when using tab indentation. You should set the tab size to match what is expected for the standards you use. For example, `WordPress` standard requires tabs, and implicitly requires a tab-spacing size of 4.

**Comment by nuvoPoint** [comment]
Thanks for the info!

Hope we can have this setting picked up from the standard again as you also mentioned.
