### ISSUE TITLE
Add a "never" option for "phpSniffer.run" setting

### ISSUE THREAD

**Issue by dossy** [wongjn/vscode-php-sniffer#28]
I don't want the formatter run automatically, either `onSave` or `onType` - I want to set it to `never` run automatically.  I only want to run it when I select `Format Document` or `Format Selection`.

**Comment by wongjn** [comment]
Use the following snippet to disable on-save formatting for PHP files:
```json
{
  "[php]": {
    "editor.formatOnSave": false
  }
}
```
Or if you have a different PHP extension you would like to use to format PHP files:
```json
{
  "[php]": {
    "editor.defaultFormatter": "<your_php.extension_name>"
  }
}
```
Formatters don't generally run on type.
