### ISSUE TITLE
Autodetect phpcs from the workspace sub-directory where the file belongs

### ISSUE THREAD

**Issue by shivapoudel** [wongjn/vscode-php-sniffer#31]
If the workspace root folder has `vendor` and `phpcs.xml.dist` then everything is okay but while developing with WordPress we have to take care of "Go to definition" for which we have to include all the project files and within inner sub-directory `phpcs.xml.dist` and vendor directory exists. How can we achieve this kind of workspace? How can this kind of configuration auto detect?

**Environment**
 - OS: Windows 10
 - VSCode version: 1.42.1
 - PHP CLI version: 7.3.5
 - squizlabs/PHP_CodeSniffer version: 3.5.4

**Extension settings**
```json
{
     "phpSniffer.autoDetect": true,
    "phpSniffer.executablesFolder": "./vendor/bin/",
    "phpSniffer.standard": "./phpcs.xml",
}
```

**Additional context**
Tried setting ` "phpSniffer.autoDetect": true` but didn't work and `phpSniffer.executablesFolder` doesn't accept `${workspaceFolder}` like variables nor `./vendor/bin` is working as it displays below error.

![image](https://user-images.githubusercontent.com/3774827/75482768-90c1a900-59cd-11ea-84ae-09b9cc073d52.png)

**Comment by shivapoudel** [comment]
For the context of WordPress development, we can't place `phpcs.xml.dist` and `vendor` dir within the workspace-folder root.

**Comment by wongjn** [comment]
I don't think `./` means the same in Windows as it does in unix-like systems — try `vendor\\bin\\` instead.

**Comment by shivapoudel** [comment]
Using `"phpSniffer.executablesFolder": "vendor\\bin\\"` but did not work?

**Comment by wongjn** [comment]
Similar error message?

**Comment by shivapoudel** [comment]
Yes, I am receiving the same error which I have stated in the above comment!

**Comment by wongjn** [comment]
The exact same error message, character for character? I just tested `vendor\\bin\\` and seems to work. Otherwise it probably says something about it cannot find the path specified, in which case you need to set `phpSniffer.executablesFolder` to where your `vendor/bin` folder actually is, relative to the workspace folder.

**Comment by shivapoudel** [comment]
@wongjn I always prefer the global installation of PHPCS so the command `phpcs` and `phpcbf` are available which means I don't have to set `phpSniffer.executablesFolder` but while choosing `phpSniffer.standard` from the `phpcs.xml` OR `phpcs.xml.dist` there exists a problem.

**Comment by shivapoudel** [comment]
![image](https://user-images.githubusercontent.com/3774827/75526351-bc7a7880-5a39-11ea-8795-f359e43a0aed.png)

I don't want to set `WordPress` as standard but just auto detect phpcs.xml file located in the directory like the screenshot above.

**Comment by wongjn** [comment]
Set `phpSniffer.standard` as `wp-content\\plugins\\everest-forms\\phpcs.xml` in the workspace folder or workspace settings should get it to work.

Alternatively, if you want to keep the functionality of `phpSniffer.autoDetect`, convert to a multi-root workspace by adding `wp-content/plugins/everest-forms` as a root folder.

**Comment by shivapoudel** [comment]
It's work but isn't there a way `phpSniffer.autoDetect` can detect different projects `phpcs.xml` file automatically?

**Comment by wongjn** [comment]
Not at the moment — something to look at in the future perhaps.

**Comment by certainlyakey** [comment]
Had the same issue - working on a WP website where the whole WP structure is represented by a VSCode workspace, but `phpcs.xml` is under a theme folder. The solution (hopefully temporary) is to make the workspace multiroot by adding the theme folder to it separately as a first root.

**Comment by certainlyakey** [comment]
Update: on another computer (a Mac as well) the technique described in the previous comment stopped working, setting the path to the `vendor/bin` folder in the workspace settings didn't help. Only installing phpcs globally made it working.
