### ISSUE TITLE
Add better error message for write EPIPE when phpcs is not found

### ISSUE THREAD

**Issue by carlituxman** [wongjn/vscode-php-sniffer#35]
On every save appear: "write EPIPE" on down-right window

**Comment by wongjn** [comment]
Please could you give me more information about your envrionment so I may be able to reproduce the issue?

**Environment**
 - OS: [e.g. Windows 10]
 - VSCode version: [e.g. 1.30.2]
 - PHP CLI version: [e.g. 7.1.26]
 - squizlabs/PHP_CodeSniffer version: [e.g. 3.4.0] (global ❌/✔)

**Extension settings**
```json
{
    "phpSniffer.run": "onSave",
    "phpSniffer.onTypeDelay": 250,
    "phpSniffer.executablesFolder": "",
    "phpSniffer.autoDetect": false,
    "phpSniffer.standard": "",
    "phpSniffer.snippetExcludeSniffs" : [],
}
```

The standard or ruleset file you are using.

**Comment by carlituxman** [comment]
After reinstall and restart it seems working fine.

VSCODE info:
Versión: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Fecha: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by brettgoss** [comment]
I get this error if the extension can't find a phpcs executable. I can reproduce pretty easily in a few scenarios:
1. With phpcs not installed in globally or in the current workspace, and with `autoDetect: false`
2. With phpcs not installed globally, but installed in the current workspace, and with `autoDetect: false`

If I change autoDetect to true, the error disappears, however it returns if I'm working on any project that doesn't have phpcs installed in it. The solution here would be to install phpcs globally, but I feel like there should be a better error to indicate that it can't find the executable.

**Comment by wongjn** [comment]
Great, thank you for that extra information.

**Comment by ortonomy** [comment]
Also, get the same error, same environment. You should just link to : `https://github.com/squizlabs/PHP_CodeSniffer` and say in README 'it must accessible on your path before using this extension'

**Comment by maccyd10** [comment]
When I added the full path to phpcs the problem was  solved.
The path must be like:

`/Users/username/.composer/vendor/bin`

not like:

`~/.composer/vendor/bin`
