### ISSUE TITLE
Why does this run when pasting code? How to turn off?

### ISSUE THREAD

**Issue by briantully** [wongjn/vscode-php-sniffer#37]
**Describe the bug**
With this extension enabled and set up to only run onSave, I still get weird issues when I paste PHP code into a document, where it always adds a docblock above the pasted code. I can't figure out how to disable this other than changing "editor.formatOnPaste" to false, which is not what I want. Is there any way to prevent the docblock from getting added on paste?

**To Reproduce**
1. open a PHP file
2. copy paste a php snippet from another file
3. code gets pasted, but above it gets added a @file docblock
4. sometimes this docblock gets added within the code you've pasted

**Expected behavior**
I would just like the code I am pasting to be added and properly indented without adding the docblock above/within it.

**Environment**
 - OS: Mac OS X 10.14.6
 - VSCode version: 1.43.2
 - PHP CLI version: PHP 7.3.14
 - squizlabs/PHP_CodeSniffer version: PHP_CodeSniffer version 3.3.2 (global ✔)

**Extension settings**
```json
{
    "phpSniffer.run": "onSave",
    "phpSniffer.onTypeDelay": 250,
    "phpSniffer.executablesFolder": "",
    "phpSniffer.autoDetect": true,
    "phpSniffer.standard": "Drupal",
    "phpSniffer.snippetExcludeSniffs" : [],
}
```

**Additional context**

**Comment by wongjn** [comment]
Add the rule that is adding the doc block to `phpSniffer.snippetExcludeSniffs` array setting.

**Comment by tyler36** [comment]
@briantully, what was the name of the rule?

**Comment by briantully** [comment]
I don't recall. It looks like I wound up uninstalling this extension and using the "PHP Sniffer & Beautifier" extension instead.

**Comment by tyler36** [comment]
Thanks for the update ... I'll look into "Drupal,DrupalPractice"
