### ISSUE TITLE
disable option

### ISSUE THREAD

**Issue by meysamkia** [wongjn/vscode-php-sniffer#38]
**Is your feature request related to a problem? Please describe.**
I have not found a way to disable the extension in the settings. Whenever I don't want the code to be sniffed I have to disable the extension from the the extensions entry, then change the workspace/user settings file, since it doesn't know about the extension anymore.

**Describe the solution you'd like**
It would be nice to have the option to disable linting in the user or workspace settings.

It is a wonderful extension.
Thanks

**Comment by wongjn** [comment]
You can leave the settings in the settings file even if you have the extension disabled — VSCode still works.
