### ISSUE TITLE
PHP Installed from ASDF not Recognized

### ISSUE THREAD

**Issue by AdsonCicilioti** [wongjn/vscode-php-sniffer#46]
![image](https://user-images.githubusercontent.com/6278398/105570302-42c13c80-5d27-11eb-927b-e086e369d18c.png)

`which php`
`/home/USER/.asdf/shims/php`

`/home/USER/.asdf/shims/` is present on $PATH. The `php`, `phpcs` and `phpcb` binaries commands response normally.

And so why this Extension can't recognize the `php` executable?

See [asdf](https://github.com/asdf-vm/asdf).

**Comment by AdsonCicilioti** [comment]
Man, somehow, after I restarted the machine everything worked.

I forgot to mention that I am using WSL2 on Windows. So I believe that this must be related to him in some way.

If you want you can close the issue or maybe you want to investigate more about it. I leave it to you.

**Comment by wongjn** [comment]
Thank you for the follow up, I'll close this!
