### ISSUE TITLE
Option to have the errors/suggestions on top of the infowindow

### ISSUE THREAD

**Issue by berengerz-vortexsolution** [wongjn/vscode-php-sniffer#50]
Love the extension. One frustration is when using other systems that give information about the functions and else, the errors/suggestions are added at the bottom, which makes it hard to see the correct problems, because it requires scrolling a lot.

![EO3R15NRz7](https://user-images.githubusercontent.com/33874943/113913078-e4461f00-97a9-11eb-8c2e-656c342b6d2f.gif)

**Describe the solution you'd like**
It could be nice to be able to toggle a setting that prepends the PHPCS errors/suggestions ON TOP of the window.
PHPStorm displays the code-sniffing messages on top.

**Describe alternatives you've considered**
No other alternative considered.

Many thanks!

**Comment by wongjn** [comment]
Thank you for submission! Unfortunately, the extension does not control where its errors appears; it tells VSCode about them and it is up to VSCode to display them. I did some searching and found the relevant feature request at microsoft/vscode#73120. I would advise +1-ing it and following it there, although it seems to be in their backlog so not sure when it would get implemented. Perhaps as a work-around for now is to use the Problems panel instead.

**Comment by berengerz-vortexsolution** [comment]
Thanks!
