### ISSUE TITLE
executablesFolder setting requires different values for windows and unix.

### ISSUE THREAD

**Issue by x-user** [wongjn/vscode-php-sniffer#54]
**Describe the bug**
Setting executablesFolder with unix path separator doesn't work on windows.

**To Reproduce**
1. install squizlabs/PHP_CodeSniffer in project sub folder.
2. set executablesFolder in project settings using unix path separator (ex: tools/phpcs/vendor/bin).
3. Open project on windows machine.

**Expected behavior**
For the executables path setting to work without modification.

**Environment**
- OS: Windows 7 Pro
- VSCode version: 1.56.2
- PHP CLI version: 8.0.1
- squizlabs/PHP_CodeSniffer version: 3.6.0 (local in ${workspaceFolder}/tools/phpcs)

**Extension settings**
```json
{
  "phpSniffer.executablesFolder": "tools/phpcs/vendor/bin"
}
```

**Additional context**
Error message
```
"tools" is not recognized as an internal or external command, operable program or batch file.
```

While platform specific settings isn't implemented in VSCode there two possible solutions:
1. Use path.normalize (as in psalm/psalm-vscode-plugin)
2. Add separate settings for windows (as in junstyle/vscode-php-cs-fixer)

**Comment by jonshipman** [comment]
You can use the VSCode variable `${pathSeparator}`

```
{
  "phpSniffer.executablesFolder": "tools${pathSeparator}phpcs${pathSeparator}vendor${pathSeparator}bin"
}
```

**Comment by x-user** [comment]
> You can use the VSCode variable `${pathSeparator}`
> 
> ```
> {
>   "phpSniffer.executablesFolder": "tools${pathSeparator}phpcs${pathSeparator}vendor${pathSeparator}bin"
> }
> ```

```json
{
  "phpSniffer.executablesFolder": "tools${/}phpcs${/}vendor${/}bin"
}
```

I forgot about this long time ago, thank you for reminder. I didn't know if path separator variable existed when i created this issue, but now it even have this short alias `${/}`, closing.
