### ISSUE TITLE
WSL help?

### ISSUE THREAD

**Issue by cemah** [wongjn/vscode-php-sniffer#55]
What can I do to enable Code Sniffing via WSL2 and DDEV/Docker? For Intelephense, I was able to fake this by using an executable bash script at `/usr/local/bin/php` as follows:

`#!/bin/bash
docker exec -i --user=1000:1000 ddev-my-container-web php "$@"`

However, a similar fake-out with `docker exec -i --user=1000:1000 ddev-my-container-web phpcs "$@"` does not work, since the Code Sniffer wants a path to a folder for phpcs and phpcbf, not a specific pointer to one executable.

**Comment by x-user** [comment]
You could try using dev containers.
[https://code.visualstudio.com/docs/remote/containers](url)

**Comment by cemah** [comment]
Thanks, looks like out of the three computers I'm using, that's the only one where I forgot to install the Remote Development extension pack. Whoops -- thanks for pointing that out.
