### ISSUE TITLE
Ignore project when using this extension

### ISSUE THREAD

**Issue by emendelski** [wongjn/vscode-php-sniffer#68]
**Is your feature request related to a problem? Please describe.**
Many times I'm using legacy code where PHPCS was never used. And extension mark every mistake on those pages (a lot of squiggly lines). I won't fix those at this moment.

<img width="880" alt="Zrzut ekranu 2023-05-12 o 12 34 52" src="https://github.com/wongjn/vscode-php-sniffer/assets/796237/271383b5-3397-4473-9521-c59cd356ff8b">

**Describe the solution you'd like**
I would like to have the option to disable this extension for a certain project (or workspace).

**Describe alternatives you've considered**
I played with the settings in VS Code but with no result.
I tried using `phpcs.xml` with exclude pattern but it doesn't work.
```xml
<?xml version="1.0"?>
<ruleset name="PHP_CodeSniffer">
    <description>PHP Code Sniffer configuration file.</description>
    <exclude-pattern>*</exclude-pattern>
</ruleset>
``` 

**Additional context**
I have installed `phpcs` globally with the path in `phpSniffer.executablesFolder`

**Comment by wongjn** [comment]
Thank you for your suggestion! This is actually already possible in VSCode – consider [disabling the extension for the particular workspace](https://code.visualstudio.com/docs/editor/extension-marketplace#_disable-an-extension).
