### ISSUE TITLE
php: No such file or directory

### ISSUE THREAD

**Issue by kjroelke** [wongjn/vscode-php-sniffer#69]
**Describe the bug**
PHP Sniffer can't find php.
![Screenshot 2023-05-17 at 11 44 05 AM](https://github.com/wongjn/vscode-php-sniffer/assets/16909402/28748282-8357-4dd6-995c-94d30df7ac4b)

**To Reproduce**
1. Save a .php file

**Expected behavior**

**Environment**
 - OS: macOS Ventura (13.13.1 (a))
 - VSCode version: 1.78.2 (Universal) // Darwin arm64 22.4.0
 - PHP CLI version: 8.2.6
 - squizlabs/PHP_CodeSniffer version: 3.7.2

**Extension settings**

```json
{
    "phpSniffer.run": "onSave",
    "phpSniffer.onTypeDelay": 250,
    "phpSniffer.executablesFolder": "",
    "phpSniffer.autoDetect": true
    "phpSniffer.standard": "./phpcs.xml.dist",
    "phpSniffer.snippetExcludeSniffs" : ["formatOnPaste"],
}
```

**Additional context**
Not sure what happened, as it _was_ working fine. `which php` outputs `/opt/homebrew/bin/php` and it's in my PATH.

**Comment by wongjn** [comment]
Thank you for the bug report. Unfortunately, I can't seem to think what could be wrong – nothing has changed in the extension code recently.

**Comment by kjroelke** [comment]
That's what I was afraid of. I'll keep digging on my end.

**Comment by kjroelke** [comment]
I'm going to close this issue. Sometimes it happens and sometimes it doesn't...seems like a coin toss with no real fix.
