### ISSUE TITLE
Parse error: syntax error, unexpected '=' in...

### ISSUE THREAD

**Issue by AlekseiGrigorev** [wongjn/vscode-php-sniffer#72]
Dear Sirs!
When I open any PHP file I get an error:
Parse error: syntax error, unexpected '=' in C:\OSPanel543\userdata\composer\vendor\symfony\string\Resources\functions.php on line 34
Source: PHP Sniffer (Extension)

The C:\OSPanel543\userdata\composer\ folder is the global composer installation folder. My project is located in a completely different folder. I'm trying to disable checking this file in .phpcs.xml with
`<ruleset name="ruleset">
<description>ruleset</description>
<arg name="ignore" value="C:/OSPanel543/userdata/composer/vendor/symfony/string/Resources/functions.php" />
<exclude-pattern>C:/OSPanel543/userdata/composer/vendor/symfony/string/Resources/functions.php</exclude-pattern>`
...
but it doesn't help

Why does the sniffer check files outside the project folder and how to disable it?

**Comment by wongjn** [comment]
I don't think it's checking it the file mentioned. It seems like you may have the [`symfony/string`](https://packagist.org/packages/symfony/string) package installed globally and you are running PHP Sniffer globally too. When PHP Sniffer runs, it loads composer packages in some way and then trips up with that file. Perhaps there is some discrepancy in PHP version compatibility?

**Comment by AlekseiGrigorev** [comment]
Thank you, [wongjn](https://github.com/wongjn)! You are absolutely right. I tried to run phpcs -i and got the same error. The plugin has nothing to do with it.
