### ISSUE TITLE
Double quoting arguments

### ISSUE THREAD

**Issue by wongjn** [wongjn/vscode-php-sniffer#8]
@wongjn this fixes don't solve the problem, still with an error:
![image](https://user-images.githubusercontent.com/16064767/51934538-f8807b80-23ea-11e9-9e5d-ba34ffc69ac1.png)

When I define PHPSniffer standard as `WordPress` show me this error:
![image](https://user-images.githubusercontent.com/16064767/51934798-94aa8280-23eb-11e9-97d1-89a7ec8445f1.png)

I think it can solve:
https://stackoverflow.com/questions/48014957/quotes-in-node-js-spawn-arguments

_Originally posted by @sergio02195 in https://github.com/wongjn/vscode-php-sniffer/issues/7#issuecomment-458678080_

**Comment by wongjn** [comment]
What OS are you running out of curiosity?

**Comment by sergio02195** [comment]
Ubuntu 18.04.1 LTS
