### ISSUE TITLE
Specify in README that one needs to use the "Format document" command to invoke phpcbf 

### ISSUE THREAD

**Issue by coccoinomane** [wongjn/vscode-php-sniffer#9]
Hello!

Thank you for this great extension, thanks to it I have completely replaced the phpcs extension 👍🏼

May I suggest to make it clear in the README how to invoke `phpcbf `?
I was expecting an ad-hoc command; it took me a while to understand that I had to format the document via the standard VS Code "Format document" and "Format selection" commands.

Thank you,
Guido

**Comment by wongjn** [comment]
Thanks for the feedback. I'll look at adding something in.
